Repository WildCodeSchool-2024-02/JS-RMT-Julien-StreetArtHunter-P3, pull requests merged in 2024-09, with the labels that each got.

#42 Hunter@feat
  client/src/assets/backgroundHunterGame.png
  client/src/components/Geolocation.jsx
  client/src/main.jsx
  client/src/pages/HunterGame.jsx
  client/src/styles/Geolocation.css
  client/src/styles/hunter-game.css
Labels: CORRECTIONS DONE

#44 mise en place du boutton addcategory
  client/src/components/modalCategory/ModalCategory.jsx
  client/src/pages/adminInterface/Category.jsx
  server/app/controllers/categoryActions.js
  server/app/router.js
  server/database/models/CategoryRepository.js
Labels: REVIEWED

#46 BackButton@feat
  client/src/assets/flecheRetour.png
  client/src/assets/loupe.png
  client/src/components/BackButton.jsx
  client/src/components/Header.jsx
  client/src/components/NavAdmin.jsx
  client/src/styles/back-button.css
Labels: REVIEWED

#47 Seen@feat
  client/src/components/NavAdmin.jsx
  client/src/components/tables/Rows.jsx
  client/src/components/tables/StatusSelect.jsx
  client/src/main.jsx
  client/src/pages/adminInterface/Seen.jsx
  client/src/styles/styles-pages/admin-interface.css
  server/app/controllers/seenActions.js
  server/app/router.js
  server/database/models/SeenRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED

#49 Global css@hotfix
  client/index.html
  client/src/assets/logo.ico
  client/src/components/Carousel.jsx
  client/src/components/Geolocation.jsx
  client/src/main.jsx
  client/src/pages/Detail.jsx
  client/src/pages/Enter.jsx
  client/src/pages/Login.jsx
  client/src/pages/Register.jsx
  client/src/styles/Geolocation.css
  client/src/styles/button-enter.css
  client/src/styles/carousel.css
  client/src/styles/detail.css
  client/src/styles/form-connection.css
  client/src/styles/form-register.css
  client/src/styles/header.css
  client/src/styles/home-enter.css
  client/src/styles/searchBar.css
  client/src/styles/styles-pages/Gallery.css
  server/app/controllers/streetartActions.js
  server/database/models/StreetartRepository.js
  server/database/schema.sql
Labels: REVIEWED

#54 page 404
  client/src/components/NotFound.jsx
  client/src/main.jsx
  client/src/styles/notfound.css
Labels: REVIEW REQUESTED, REVIEWED

#55 Editartist@feat
  client/src/components/modalArtists/ModalArtist.jsx
  client/src/pages/adminInterface/Artist.jsx
  server/app/controllers/artistActions.js
  server/app/router.js
  server/app/services/validation/artist.js
  server/database/models/ArtistRepository.js
Labels: REVIEW REQUESTED

#59 Fixbis
  client/src/components/Carousel.jsx
  client/src/components/FormRegister.jsx
  client/src/components/Geolocation.jsx
  client/src/components/NavAdmin.jsx
  client/src/pages/Login.jsx
  client/src/pages/Register.jsx
  client/src/styles/Geolocation.css
  client/src/styles/button.css
  client/src/styles/header.css
Labels: REVIEWED
